(library
 (name dose_common)
 (public_name opam-solver.dose4_common)
 (flags :standard -w +A-4)
 (libraries ocamlgraph cudf re.pcre unix)
 (modules cudfAdd cudfSolver edosSolver util))

(library
 (name dose_algo)
 (public_name opam-solver.dose4_algo)
 (flags :standard -w +A-4 -open Dose_common)
 (libraries ocamlgraph cudf re.pcre opam-solver.dose4_common)
 (modules defaultgraphs depsolver depsolver_int diagnostic))
