# NB If minimum OCaml version for Dune changes, update DUNE_SECONDARY in configure.ac
URL_dune-local = https://github.com/ocaml/dune/archive/7ea41f6ef51fb6e4be8b7292dadf9c8279de87d0.tar.gz
MD5_dune-local = bcbb4744312be4cde394b0596fc24ade
